-- MySQL Script generated by MySQL Workbench
-- 04/19/16 22:56:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wc_core
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wc_core
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wc_core` DEFAULT CHARACTER SET utf8 ;
USE `wc_core` ;

-- -----------------------------------------------------
-- Table `wc_core`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_core`.`type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL COMMENT 'item or folder, text or multitext or rte or image or option or multioption or check or radio or link or datasource, language or history, layout or module',
  `description` TINYTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wc_core`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_core`.`profile` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `address` TINYTEXT NULL,
  `avatar` BLOB NOT NULL,
  `created_date` DATETIME NULL,
  `created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wc_core`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_core`.`role` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wc_core`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_core`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wc_core`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_core`.`user` (
  `id` INT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `profile_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`, `profile_id`, `role_id`, `group_id`),
  INDEX `fk_user_profile1_idx` (`profile_id` ASC),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  INDEX `fk_user_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_user_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `wc_core`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `wc_core`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `wc_core`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wc_core`.`domain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_core`.`domain` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL COMMENT 'domain of item : shema or object or assets or content',
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wc_core`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_core`.`item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NULL,
  `slug` VARCHAR(150) NULL,
  `type_id` INT UNSIGNED NOT NULL COMMENT 'type_id (item or folder)',
  `created_date` DATETIME NULL,
  `created_by` INT NOT NULL,
  `parent_id` INT UNSIGNED NOT NULL,
  `domain_id` INT NOT NULL,
  PRIMARY KEY (`id`, `type_id`, `created_by`, `domain_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_item_item1_idx` (`parent_id` ASC),
  INDEX `fk_item_type1_idx` (`type_id` ASC),
  INDEX `fk_item_user1_idx` (`created_by` ASC),
  INDEX `fk_item_domain1_idx` (`domain_id` ASC),
  CONSTRAINT `fk_item_item1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `wc_core`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `wc_core`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `wc_core`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_domain1`
    FOREIGN KEY (`domain_id`)
    REFERENCES `wc_core`.`domain` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wc_core`.`field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_core`.`field` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `type_id` INT UNSIGNED NOT NULL COMMENT 'type_id (text, multitext, etc)',
  `placeholder` VARCHAR(255) NULL COMMENT 'standard / default value of this field',
  `item_id` INT UNSIGNED NOT NULL COMMENT 'item_id behalf as parent of this field',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`id`, `type_id`, `item_id`, `created_by`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_field_item_idx` (`item_id` ASC),
  INDEX `fk_field_type1_idx` (`type_id` ASC),
  INDEX `fk_field_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_field_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `wc_core`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_field_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `wc_core`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_field_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `wc_core`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wc_core`.`presentation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_core`.`presentation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `route` VARCHAR(45) NULL,
  `view` VARCHAR(45) NULL,
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `type_id` INT UNSIGNED NOT NULL COMMENT 'type_id (layout or module)',
  PRIMARY KEY (`id`, `created_by`, `type_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_presentation_type1_idx` (`type_id` ASC),
  INDEX `fk_presentation_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_presentation_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `wc_core`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presentation_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `wc_core`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wc_core`.`version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_core`.`version` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` TINYTEXT NULL,
  `type_id` INT UNSIGNED NOT NULL COMMENT 'type_id (language or history)',
  `item_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `type_id`, `item_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_version_item1_idx` (`item_id` ASC),
  INDEX `fk_version_type1_idx` (`type_id` ASC),
  CONSTRAINT `fk_version_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `wc_core`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_version_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `wc_core`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wc_core`.`asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_core`.`asset` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NOT NULL,
  `summary` TINYTEXT NULL,
  `file` BLOB NOT NULL,
  `type_id` INT UNSIGNED NOT NULL COMMENT 'type_id (image or video or document)',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `parent_id` INT UNSIGNED NOT NULL COMMENT 'item_id of item behalf as parent of this asset',
  PRIMARY KEY (`id`, `item_id`, `type_id`, `created_by`, `parent_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_asset_type1_idx` (`type_id` ASC),
  INDEX `fk_asset_item1_idx` (`parent_id` ASC),
  INDEX `fk_asset_user1_idx` (`created_by` ASC),
  INDEX `fk_asset_item2_idx` (`item_id` ASC),
  CONSTRAINT `fk_asset_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `wc_core`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_item1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `wc_core`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `wc_core`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_item2`
    FOREIGN KEY (`item_id`)
    REFERENCES `wc_core`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wc_core`.`webpart_schema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_core`.`webpart_schema` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `as_navigation` VARCHAR(3) NULL,
  `presentation_id` INT UNSIGNED NOT NULL,
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `item_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `presentation_id`, `created_by`, `item_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_webpage_schema_presentation1_idx` (`presentation_id` ASC),
  INDEX `fk_webpage_schema_user1_idx` (`created_by` ASC),
  INDEX `fk_webpart_schema_item1_idx` (`item_id` ASC),
  CONSTRAINT `fk_webpage_schema_presentation1`
    FOREIGN KEY (`presentation_id`)
    REFERENCES `wc_core`.`presentation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_webpage_schema_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `wc_core`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_webpart_schema_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `wc_core`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
