-- MySQL Script generated by MySQL Workbench
-- 04/19/16 22:57:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wc_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wc_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wc_web` DEFAULT CHARACTER SET utf8 ;
USE `wc_web` ;

-- -----------------------------------------------------
-- Table `wc_web`.`landing_page_schema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wc_web`.`landing_page_schema` (
  `id` INT NOT NULL,
  `summary` TINYTEXT NULL,
  `description` TEXT NULL,
  `datasource` BLOB NULL,
  `published_date` DATETIME NULL,
  `created_by` INT NOT NULL,
  `webpart_schema_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `created_by`, `webpart_schema_id`),
  INDEX `fk_landing_page_schema_user1_idx` (`created_by` ASC),
  INDEX `fk_landing_page_schema_webpage_schema1_idx` (`webpart_schema_id` ASC),
  CONSTRAINT `fk_landing_page_schema_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `wc_web`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_landing_page_schema_webpage_schema1`
    FOREIGN KEY (`webpart_schema_id`)
    REFERENCES `wc_web`.`webpart_schema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
